minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080
blockExoticSubdeps: true

overrides:
  postcss: 8.5.15

allowBuilds:
  sharp: true
  unrs-resolver: true
